spring:
  application:
    name: activityms
  data:
    mongodb:
      uri: mongodb://localhost:27017/activitydb
      database: activitydb
server:
  port: 8082
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true