spring:
  application:
    name: userms
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: syphe
    password: syphe
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8081